datatemp<-read.table("household_power_consumption.txt", nrow = 10, header = TRUE, sep=";")
classes<-sapply(datatemp, class)
data<-read.table("household_power_consumption.txt", header = TRUE, sep=";", colClasses = classes,na.strings="?")
useddata1<-subset(data, Date == "1/2/2007")
useddata2<-subset(data, Date == "2/2/2007")
useddata<-merge(useddata1, useddata2, all=TRUE)

DateTime<-paste(useddata$Date, useddata$Time)
condate <- strptime(DateTime, "%d/%m/%Y %H:%M:%S")
par(mar=c(2,4,1,1))
par(mfrow=c(2,2))
plot(condate, useddata$Global_active_power,ylab="Global Active Power",xlab="", type="l",col="black")
plot(condate, useddata$Voltage,ylab="Voltage",xlab="daytime", type="l",col="black")
plot(condate, useddata$Sub_metering_1,ylab="Energy sub metering",xlab="", type="l",col="black")
points(condate, useddata$Sub_metering_2,type="l",col="red")
points(condate, useddata$Sub_metering_3,type="l",col="blue")
legend("topright",pch="_",col=c("black","red","blue"), legend=c("Sub_metering_1               ","Sub_metering_2               ","Sub_metering_3              "), box.lty=0,inset = 0.02)
plot(condate, useddata$Global_reactive_power,ylab="Global_reactive_power",xlab="daytime", type="l",col="black")
dev.copy(png,file="plot4.png")
dev.off()

