datatemp<-read.table("household_power_consumption.txt", nrow = 10, header = TRUE, sep=";")
classes<-sapply(datatemp, class)
data<-read.table("household_power_consumption.txt", header = TRUE, sep=";", colClasses = classes,na.strings="?")
useddata1<-subset(data, Date == "1/2/2007")
useddata2<-subset(data, Date == "2/2/2007")
useddata<-merge(useddata1, useddata2, all=TRUE)

DateTime<-paste(useddata$Date, useddata$Time)
condate <- strptime(DateTime, "%d/%m/%Y %H:%M:%S")
par(mfrow=c(1,1))
plot(condate, useddata$Sub_metering_1,ylab="Energy sub metering",xlab="", type="l",col="black")
points(condate, useddata$Sub_metering_2,type="l",col="red")
points(condate, useddata$Sub_metering_3,type="l",col="blue")
legend("topright",pch="_",col=c("black","red","blue"), legend=c("Sub_metering_1                    ","Sub_metering_2                    ","Sub_metering_3                    "))
dev.copy(png,file="plot3.png")
dev.off()

